# TX/RX app halves (split-streamer D1 / SA-T4).
set(VSTREAMER_APP_TX_OK OFF)
if(ENABLE_STREAM_SENDER AND ENABLE_RTP_H264_PAY)
    if(ENABLE_H264_ENCODER_MPP OR ENABLE_H264_ENCODER_CEDAR OR ENABLE_H264_ENCODER_INTEL)
        if(ENABLE_NOISE_SOURCE OR ENABLE_V4L2_SOURCE)
            if(NOT ENABLE_V4L2_SOURCE OR ENABLE_JPEG_DECODER_MULTICORE)
                set(VSTREAMER_APP_TX_OK ON)
            endif()
        endif()
    endif()
endif()

set(VSTREAMER_APP_RX_OK OFF)
if(ENABLE_STREAM_RECEIVER AND ENABLE_RTP_H264_DEPAY AND ENABLE_H264_DECODER_MPP AND
   ENABLE_SDL_SINK)
    set(VSTREAMER_APP_RX_OK ON)
endif()

message(STATUS "  VSTREAMER_APP_TX_OK=${VSTREAMER_APP_TX_OK}")
message(STATUS "  VSTREAMER_APP_RX_OK=${VSTREAMER_APP_RX_OK}")
